const fs = require('fs');
const data = JSON.parse(fs.readFileSync('config/settings_schema.json', 'utf8'));

const translations = {
  "Colors": "Colores",
  "General colors": "Colores generales",
  "Primary Color": "Color principal",
  "Secondary Color": "Color secundario",
  "Body Color": "Color del cuerpo",
  "Text Color": "Color del texto",
  "Background Color": "Color de fondo",
  "Extra Background Color": "Color de fondo extra",
  "Heading Color": "Color del encabezado",
  "Section Heading Color": "Color del título de sección",
  "Paragraph Color": "Color del párrafo",
  "Theme Border Color": "Color del borde del tema",
  "Theme Border Color Opacity": "Opacidad del borde del tema",
  "Typography": "Tipografía",
  "Body Font Family": "Familia de fuentes del cuerpo",
  "Font Family": "Familia de fuentes",
  "Body Custom Font Family": "Fuente personalizada del cuerpo",
  "Use Custom Font": "Usar fuente personalizada",
  "Custom Font": "Fuente personalizada",
  "[Find more Google fonts](https://fonts.google.com)": "[Encuentra más fuentes de Google](https://fonts.google.com)",
  "Font Weight": "Grosor de fuente",
  "Subtitle Font Weight": "Grosor de fuente del subtítulo",
  "Font Style": "Estilo de fuente",
  "Italic": "Cursiva",
  "Normal": "Normal",
  "Oblique": "Oblicua",
  "Unset": "No establecido",
  "Body Common Propoerty": "Propiedades comunes del cuerpo",
  "Font Size": "Tamaño de fuente",
  "Letter Spacing": "Espaciado de letras",
  "Heading Font Family": "Familia de fuentes de encabezados",
  "Heading Custom Font Family": "Fuente personalizada de encabezados",
  "Section Heading Font Family": "Familia de fuentes de título de sección",
  "Section Heading Custom Font Family": "Fuente personalizada de título de sección",
  "Section Heading Common Propoerty": "Propiedades comunes de título de sección",
  "Text Property": "Transformación de texto",
  "Capitalize": "Capitalizar",
  "Lowercase": "Minúsculas",
  "Uppercase": "Mayúsculas",
  "None": "Ninguno",
  "Paragraph Font Family": "Familia de fuentes del párrafo",
  "Paragraph Custom Font Family": "Fuente personalizada del párrafo",
  "Paragraph Common Propoerty": "Propiedades comunes del párrafo",
  "Font Line Height": "Altura de línea de fuente",
  "Other Font Family": "Otra familia de fuentes",
  "Other Custom Font Family": "Otra fuente personalizada",
  "Input, Select, Textarea Type": "Tipos de Input, Select, Textarea",
  "Tag Propoerty": "Propiedades de etiqueta",
  "Border Color": "Color del borde",
  "Border Color Opacity": "Opacidad del borde",
  "Border Radius": "Radio del borde",
  "RTL Version": "Versión RTL",
  "RTL version enable": "Habilitar versión RTL (derecha a izquierda)",
  "RTL Enable": "Habilitar RTL",
  "Google Analytics": "Google Analytics",
  "Enable Google Analytics": "Habilitar Google Analytics",
  "Tracking Id": "ID de seguimiento",
  "Get Tracking Id [here](https://analytics.google.com/)": "Obtén tu ID de seguimiento [aquí](https://analytics.google.com/)",
  "Newsletter Popup": "Ventana emergente del boletín (Newsletter)",
  "Newsletter": "Boletín (Newsletter)",
  "Newsletter Popup Enable": "Habilitar ventana emergente",
  "Newsletter Content": "Contenido del boletín",
  "Background Image": "Imagen de fondo",
  "Recommended Size: 250px x 400px": "Tamaño recomendado: 250px x 400px",
  "Title": "Título",
  "Description": "Descripción",
  "Newsletter Success Text": "Texto de éxito",
  "Coupan Code": "Código de cupón",
  "Email Placeholer": "Texto temporal del email",
  "Input Text Color": "Color del texto del input",
  "Company Logo": "Logotipo de la empresa",
  "Header Logo": "Logo del encabezado",
  "Logo Width": "Ancho del logo",
  "Logo Image": "Imagen del logo",
  "Recommended Size: 105px x 22px": "Tamaño recomendado: 105px x 22px",
  "Footer Logo": "Logo del pie de página",
  "Favicon": "Favicon",
  "Favicon Image": "Imagen del Favicon",
  "Will be scaled down to 32 x 32px": "Se escalará a 32 x 32px",
  "Tooltip": "Tooltip (Mensaje emergente)",
  "Tooltip Title": "Título del Tooltip",
  "Show Tooltip": "Mostrar Tooltip",
  "Add To Cart Tooltip Title": "Título del Tooltip Agregar al carrito",
  "Wishlist Tooltip Title": "Título del Tooltip Lista de deseos",
  "Quickview Tooltip Title": "Título del Tooltip Vista rápida",
  "Soldout Tooltip Title": "Título del Tooltip Agotado",
  "Product Hover Option": "Opción de cursor sobre producto",
  "Product Hover": "Cursor sobre producto (Hover)",
  "Show Second Image On Hover For Desktop": "Mostrar segunda imagen al pasar el cursor (Escritorio)",
  "Show Second Image On Hover For Mobile": "Mostrar segunda imagen al pasar el cursor (Móvil)",
  "This option for product hover if you want to show second image on hover click on above checkbox": "Esta opción permite mostrar una segunda imagen cuando el usuario pasa el cursor sobre el producto",
  "Product Reviews Option": "Opción de reseñas de productos",
  "Product Review": "Reseña de producto",
  "Show Product Review": "Mostrar reseña de producto",
  "Install Free Apps for Product Review [Click Here](https://apps.shopify.com/product-reviews)": "Instala apps gratuitas para reseñas [Haz clic aquí](https://apps.shopify.com/product-reviews)",
  "Product Category": "Categoría de producto",
  "Show Product Category": "Mostrar categoría de producto",
  "Product Timer": "Temporizador de producto",
  "Countdown Timer": "Temporizador de cuenta regresiva",
  "Day Title": "Título de día",
  "Hour Title": "Título de hora",
  "Minute Title": "Título de minuto",
  "Second Title": "Título de segundo",
  "Show Text": "Mostrar texto",
  "Cuntdown timer comes from metafield": "El temporizador de cuenta regresiva proviene de metacampos",
  "Mini Cart": "Mini Carrito",
  "Item Title": "Título del artículo",
  "When Cart Is Empty": "Cuando el carrito está vacío",
  "Empty Cart": "Carrito vacío",
  "Button Label": "Etiqueta del botón",
  "Link": "Enlace",
  "When Cart Is Not Empty": "Cuando el carrito no está vacío",
  "Cart Text1": "Texto del carrito 1",
  "Cart Text2": "Texto del carrito 2",
  "Cart Sub-total": "Subtotal del carrito",
  "Product Quickview": "Vista rápida del producto",
  "Show Product Quickview": "Mostrar vista rápida",
  "quick view title": "Título de vista rápida",
  "Add to cart title": "Título de agregar al carrito",
  "For search": "Para búsqueda",
  "Search": "Buscar",
  "Search option": "Opción de búsqueda",
  "Show Search": "Mostrar barra de búsqueda",
  "Search placeholder Text": "Texto temporal de búsqueda",
  "Placeholder Text": "Texto temporal",
  "Search Autocomplete": "Autocompletar de búsqueda",
  "Which product you were find text": "Texto 'Qué producto estabas buscando'",
  "Find Text 1": "Texto de búsqueda 1",
  "Find Text 2": "Texto de búsqueda 2",
  "When search item is 'Empty'": "Cuando la búsqueda está 'Vacía'",
  "Find Empty Text": "Texto de búsqueda vacía",
  "When search item is 'Not Empty'": "Cuando la búsqueda 'No está vacía'",
  "Find URL Text": "Texto de URL de búsqueda",
  "Breadcrumb": "Migas de pan (Breadcrumb)",
  "Show Breadcrumb": "Mostrar migas de pan",
  "Section Padding": "Relleno de sección (Padding)",
  "Section Padding Top": "Relleno superior de sección",
  "Section Padding Bottom": "Relleno inferior de sección",
  "Mobile padding": "Relleno en móviles",
  "Show Background Image": "Mostrar imagen de fondo",
  "Breadcrumb Background Image": "Imagen de fondo de las migas de pan",
  "Default Image Size: 1920px X 300px": "Tamaño de imagen por defecto: 1920px X 300px",
  "Breadcrumb Background Image Overlay Color": "Color superpuesto de imagen de fondo",
  "Breadcrumb Background Image Overlay Color Opacity": "Opacidad del color superpuesto de fondo",
  "Breadcrumb Background Color": "Color de fondo de las migas de pan",
  "Bottom Border": "Borde inferior",
  "Show Breadcrumb Border": "Mostrar borde de las migas de pan",
  "Breadcrumb text color": "Color del texto de migas de pan",
  "Breadcrumb title color": "Color del título de migas de pan",
  "Breadcrumb list text color": "Color de la lista de migas de pan",
  "Blog/Article Sidebar": "Barra lateral de Blog/Artículo",
  "Search Placeholder": "Texto temporal de búsqueda",
  "Read More Button": "Botón Leer Más",
  "Button Text": "Texto del botón",
  "Button Style": "Estilo de botón",
  "Button Style1": "Estilo de botón 1",
  "Button Style2": "Estilo de botón 2",
  "Button Style3": "Estilo de botón 3",
  "placeholder": "texto temporal",
  "Archive": "Archivo",
  "Recent Posts": "Publicaciones recientes",
  "How Many Post Show": "Cuántas publicaciones mostrar",
  "Tags": "Etiquetas",
  "How Many Tags Show": "Cuántas etiquetas mostrar",
  "Social Media": "Redes Sociales",
  "For Facebook": "Para Facebook",
  "Social Icon Name": "Nombre del icono social",
  "[See Icon Name](https://remixicon.com)": "[Ver nombre del icono](https://remixicon.com)",
  "For Instagram": "Para Instagram",
  "For Twitter": "Para Twitter",
  "For Dribbble": "Para Dribbble",
  "Payment Icon": "Iconos de pago",
  "Payment Providers": "Proveedores de pago",
  "Payment Providers Name": "Nombre de los proveedores de pago",
  "Ex: afterpay, american_express, apple_pay, bitcoin, dankort, diners_club, discover, dogecoin, dwolla, forbrugsforeningen, google_pay, ideal, jcb, klarna, klarna-pay-later, litecoin, maestro, master, paypal, shopify_pay, sofort, visa, paytm": "Ej: afterpay, american_express, apple_pay, bitcoin, dankort, diners_club, discover, dogecoin, dwolla, forbrugsforeningen, google_pay, ideal, jcb, klarna, klarna-pay-later, litecoin, maestro, master, paypal, shopify_pay, sofort, visa, paytm",
  "Payment Providers Icon": "Iconos de proveedores de pago",
  "Icon Width": "Ancho del icono",
  "Set 'SVG' icon 'Width' from here": "Establece el 'Ancho' del icono 'SVG' desde aquí",
  "Wishlist": "Lista de deseos",
  "Show Wishlist": "Mostrar lista de deseos",
  "Add Wishlist Title": "Título de añadir a la lista de deseos",
  "Loding Wishlist Title": "Título de cargando lista de deseos",
  "Remove Wishlist Title": "Título de eliminar de la lista de deseos",
  "Go To Wishlist Title": "Título de ir a la lista de deseos",
  "Wishlist Page": "Página de la lista de deseos",
  "If you want to create wishlist page then follow this URL - [Click Here](https://image.prntscr.com/image/ZEjtoJDoQwGoWloMSwt3kQ.jpeg)": "Si quieres crear la página de la lista de deseos, sigue esta URL - [Haz clic aquí](https://image.prntscr.com/image/ZEjtoJDoQwGoWloMSwt3kQ.jpeg)",
  "Wishlist Empty Title": "Título de lista de deseos vacía",
  "Login Request Title": "Título de solicitud de inicio de sesión",
  "Customer Page": "Página del cliente",
  "Login": "Iniciar sesión",
  "Create Account Title": "Título de crear cuenta",
  "Register": "Registrarse",
  "My Account / Order": "Mi Cuenta / Pedido",
  "Logout Title": "Título de cerrar sesión",
  "Custom, Default and Customer Page": "Páginas Custom, Predeterminada y Cliente",
  "Desktop / Laptop": "Escritorio / Portátil",
  "Padding Top": "Relleno superior",
  "Padding Bottom": "Relleno inferior",
  "Ipad Pro / Ipad": "Ipad Pro / Ipad",
  "Mobile": "Móvil"
};

function traverse(obj) {
  if (Array.isArray(obj)) {
    obj.forEach(traverse);
  } else if (obj !== null && typeof obj === 'object') {
    for (const [key, value] of Object.entries(obj)) {
      if (['name', 'label', 'content', 'info'].includes(key) && typeof value === 'string') {
        if (translations[value]) {
          obj[key] = translations[value];
        }
      }
      if (key === 'options' && Array.isArray(value)) {
        value.forEach(opt => {
          if (opt.label && translations[opt.label]) {
            opt.label = translations[opt.label];
          }
        });
      }
      traverse(value);
    }
  }
}
traverse(data);
fs.writeFileSync('config/settings_schema.json', JSON.stringify(data, null, 2));
console.log("Translation complete!");
